# Generated by cucumber-sinatra. (2011-09-11 15:02:47 -0400)

ENV['RACK_ENV'] = 'test'

require 'bundler'
Bundler.require(:test)
require File.join(File.dirname(__FILE__), '..', '..', 'lib/termvana.rb')
require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.default_host = "http://127.0.0.1"
Capybara.server_port = 5432
Capybara.app_host = "http://127.0.0.1:5432"
Thread.new {
  puts "Running server"
  Thin::Logging.silent = true
  Termvana.start
  puts "server is running"
}
Capybara.run_server = false
sleep 2
Capybara.app = Termvana

Capybara.javascript_driver = :webkit

class MyAppWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  MyAppWorld.new
end

